### ISSUE TITLE
Not cleaning linker flags

### ISSUE THREAD

**Issue by tcurdt** [CocoaPods/cocoapods-deintegrate#11]
see https://github.com/CocoaPods/CocoaPods/issues/4457

**Comment by pyanfield** [comment]
I got the same issue and removed the linker flags manually.

**Comment by segiddins** [comment]
Can either of you share a project that demonstrates this issue? Since I can't think of how those flags would be added anywhere but via the XCConfig.

**Comment by tcurdt** [comment]
Sorry, not anymore.

Could an old cocoapods version have put them there?

**Comment by segiddins** [comment]
Maybe?

**Comment by bfalling** [comment]
I think this is related. The "Pods.framework" entry under Project > Targets > (Main app target) > Link Binary With Libraries was not removed by running "pod deintegrate".

![pasted_image_11_18_15__9_47_pm](https://cloud.githubusercontent.com/assets/1231433/11263298/4ab92708-8e3e-11e5-897d-680d9a60761e.png)

**Comment by bfalling** [comment]
And this reference too, in the Project Navigator:
![pasted_image_11_18_15__9_53_pm](https://cloud.githubusercontent.com/assets/1231433/11263357/e281dd28-8e3e-11e5-9cf6-44863b1fc626.png)

**Comment by segiddins** [comment]
@bfalling please share a project?

**Comment by bfalling** [comment]
@segiddins Oooo hmmm... I will see if I can.

My project got all wonky with the xcconfig files that `pod install` was creating (alternating between "Pods-Appname.debug.xcconfig" and "Pods.debug.xcconfig", and complaining about whichever wasn't present! any idea why?), which is why I used deintegrate to try to reset the world.

It worked perfectly, except for the two artifacts noted above. If I can recreate that state, I'll include a project forthwith!

**Comment by segiddins** [comment]
That'll actually be fixed by an open PR I have on CocoaPods

**Comment by bfalling** [comment]
Bless you!!!

**Comment by segiddins** [comment]
This has now been fixed on CocoaPods master.
